/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="max-w-screen-lg m-auto px-3 min-h-[calc(100svh-64px)] flex items-center justify-center">
      {children}
    </main>
  );
}
