import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ZustandProvider from "@/core/providers/ZustandProvider";
import TokenTimerProvider from "@/core/providers/TokenTimerProvider";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ZustandProvider>
          <TokenTimerProvider>
            <ToastContainer className="top-[64px]" />
            <Navbar /> {children}
          </TokenTimerProvider>
        </ZustandProvider>
      </body>
    </html>
  );
}
